version: "3"

services:
  app:
    build: .
    tty: true
    ports:
      - 8080:8080
    working_dir: /app
    volumes:
      - ..:/app:delegated
      - node_modules:/app/node_modules

volumes:
  node_modules:
